# ------------------------------------------------
# 网站基础设置 (顶级键)
# ------------------------------------------------
base_url = "https://sueda-moi.github.io/my_blog"
title = "My Zola Blog"
description = "A blog built with Zola"

compile_sass = true
build_search_index = false
generate_feeds = false
minify_html = true

# ------------------------------------------------
# Markdown 配置
# ------------------------------------------------
[markdown]
highlight_code = true
highlight_theme = "css"

# ------------------------------------------------
# [extra] 主表
# ------------------------------------------------
[extra]


# ------------------------------------------------
# Taxonomy 
# ------------------------------------------------
[[taxonomies]]
name = "tags"
paginate_by = 5