version: '3.8'

services:
  zola:
    image: ghcr.io/getzola/zola:v0.19.1
    command: serve --interface 0.0.0.0 --base-url 127.0.0.1
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "1111:1111"